### ISSUE TITLE
Manual básico de Uso

### ISSUE THREAD

**Issue by nielsenag** [marceloalencar/govbr-ds-joomla#1]
Como faço pra utilizar o template?
Está funcional?
Gostaria de contribuir com o projeto

**Comment by marceloalencar** [comment]
O template pode ser instalado baixando o código-fonte no formato .zip e instalando por meio do envio deste arquivo.
Atualmente não está em condições de uso. Apenas o cabeçalho e o rodapé estão corretamente implementados.

**Comment by marceloalencar** [comment]
@nielsenag Boa tarde! Queira verificar o arquivo [README.md](https://github.com/marceloalencar/govbr-ds-joomla/blob/master/README.md) que foi adicionado no commit https://github.com/marceloalencar/govbr-ds-joomla/commit/14974031ab68738e7d8ad139240f2126235c5969 para realizar testes.
Aguardo retorno!

**Comment by marceloalencar** [comment]
Considerar-se-á resolvido este problema.
