### ISSUE TITLE
Responsividade, correção da numeração do tipo de atendimento e sugestão

### ISSUE THREAD

**Issue by anselmolopes** [marceloalencar/govbr-ds-joomla#17]
@marceloalencar  comecei a testar o template ontem e gostaria de contribuir com:

### Responsividade
Incluir a metadata para responsividade `$this->setMetaData('viewport', 'width=device-width, initial-scale=1');` antes ou depois da linha https://github.com/marceloalencar/govbr-ds-joomla/blob/14974031ab68738e7d8ad139240f2126235c5969/index.php#L37

**Observação**: fazer o mesmo no arquivo `error.php`

### Link da numeração do tipo de atendimento

Ao testar o acesso dos itens para o FalaBR estando logado no serviço e sendo direcionado para SIORG informada no template, notei que para os itens  **Elogio**  e  **Reclamação**, os serviços não são os correspondentes. Creio que os links foram implementados como estão disposto no próprio portal gov.br, o qual está direcionando erroneamente.

Para corrigir, alterar as numerações dos tipos como a seguir:

- tipo=4 para tipo=3 na 

https://github.com/marceloalencar/govbr-ds-joomla/blob/14974031ab68738e7d8ad139240f2126235c5969/index.php#L218

-  e tipo=3 para tipo=2 na 

https://github.com/marceloalencar/govbr-ds-joomla/blob/14974031ab68738e7d8ad139240f2126235c5969/index.php#L227

### Sugestão

Sugerir que seja opcional, ou que não seja incluído o título do site ao lado da logo no `menu-header`, pois dependendo da logo o título fica mal ajustado com a logo e o button do `menu-close`. Na minha opinião acho desnecessário repetir o título no `menu-header`, já que o mesmo está informado no `<header>`.

 Tornar opcional na configuração do template, ou retirar `<span><?php echo $this->params->get('texto_titulo', 'Template básico'); ?></span>` na https://github.com/marceloalencar/govbr-ds-joomla/blob/14974031ab68738e7d8ad139240f2126235c5969/index.php#L131

**Observação**: fazer o mesmo no arquivo `error.php`

**Comment by marceloalencar** [comment]
Novamente agradeço pelas contribuições.
As alterações sugeridas foram aplicadas em https://github.com/marceloalencar/govbr-ds-joomla/commit/f12338f93a08d16d11c2be4684f98406f3979e2a.
