### ISSUE TITLE
Sugestão para Parâmetros

### ISSUE THREAD

**Issue by anselmolopes** [marceloalencar/govbr-ds-joomla#18]
@marceloalencar assim como utilizou como escolhas no parâmetro **Cor do rodapé** as opções **Escuro** e **Claro**, sugiro a mesma ideia para os parâmetros **Largura** e **Menu principal**. Minhas sugestões são as seguintes mudanças das linhas 40 à 49 no arquivo `templateDetails.xml`:

`<field name="largura" type="radio" layout="joomla.form.field.radio.switcher" default="0" label="Largura do conteúdo">`
	`<option value="0">Fixa</option>`
	`<option value="1">Fluida</option>`
`</field>`
`<field name="tipomenu" type="radio" layout="joomla.form.field.radio.switcher" default="0" label="Menu principal">`
	`<option value="0">Flutuante</option>`
	`<option value="1">Empurrando</option>`
`</field>`

Uma observação é que, no código atual, tem o parâmetro **Menu principal flutuantel**,  com default="1" equivalendo a **Sim** e como resposta ele está transformando para `br-menu-push`, ou seja, empurrando, não correspondendo a escolha.

**Comment by marceloalencar** [comment]
Bom dia! Primeiramente agradeço pelas contribuições.
As alterações sugeridas foram aplicadas em https://github.com/marceloalencar/govbr-ds-joomla/commit/6fbb3a87f3a85b4c5cdc6974993ad112d63ecf06.
