### ISSUE TITLE
Menu Principal e Busca no error.php

### ISSUE THREAD

**Issue by anselmolopes** [marceloalencar/govbr-ds-joomla#21]
### MENU PRINCIPAL

@marceloalencar estou tentando colocar um item no menu principal como na figura abaixo. Ou seja, como um item de nível 1

![menuprincipal](https://github.com/marceloalencar/govbr-ds-joomla/assets/107046598/bb7777c8-ef05-43fd-98d6-f8a6da5855a3)

Ocorre que quando adiciono ao menu o módulo na posição `menu-body` e layout `menuprincipal` ele não cria um item de nível 1 e sempre aparece com o dropdown, além de não ser possível colocar uma url.

Seria o caso de se criar um tipo de módulo? Ou não estou conseguindo ver uma maneira mais simples de se resolver isso?

### BUSCA NO ERROR.PHP

Uma outra questão é sobre o item de busca na página `error.php` que não está funcionando.
Creio que seja necessária a inserção de um form e get a partir da https://github.com/marceloalencar/govbr-ds-joomla/blob/2f2aef8cf79ef38726cf3fa1cf7133316087d85e/error.php#L257

Acredito que fazendo algo como no `default.php`  do `mod_finder` a partir da linha
https://github.com/marceloalencar/govbr-ds-joomla/blob/2f2aef8cf79ef38726cf3fa1cf7133316087d85e/html/mod_finder/default.php#L40-L49
e posteriormente usando a ideia do `index.php` na https://github.com/marceloalencar/govbr-ds-joomla/blob/2f2aef8cf79ef38726cf3fa1cf7133316087d85e/index.php#L119

**Comment by marceloalencar** [comment]
Agradeço pelos comentários.
Implementei a busca na página de erro, passei batido e nem lembrava que faltava esse campo.
Sobre itens de nível 1 no menu principal, realmente não pensei nesse caso e ainda não consegui pensar em uma forma de implementar.

**Comment by anselmolopes** [comment]
Sobre o item de nível 1, estava pensando em um layout menuprincipal_nivel1, pois o que você implementou é menuprincipal do tipo folder,
https://github.com/marceloalencar/govbr-ds-joomla/blob/608f8d3fcec464924d4d96f5d662009ebfa4f824/html/layouts/chromes/menuprincipal.php#L32-L35

Creio que pode ser uma forma.

**Comment by marceloalencar** [comment]
Agradeço pela sugestão. Foi implementado o layout menuprincipal_nivel1 para exibição de itens de nível 1 no menu principal.
